회원가입 페이지 퍼블리싱 완료
Picnic-GSM/GOOUT pull request #9
Opened 2021-09-08 14:03 UTC by hyein0112

### 회원가입 페이지 퍼블리싱 완료했습니다🤓

- `backgroundView` 생성으로 배경 완성
- `emailLabel`과 `emailTextfield`생성
- `passwordLabel`과 `passwordTextfield`생성
- `checkPasswordLabel`과 `checkPasswordTextfield`생성
- 회원 가입 버튼 생성

### 코드리뷰 부탁합니다🐸

2021-09-09 10:54 UTC, Y00ujin approved these changes
수고했어요 😃😃

2021-09-09 10:58 UTC, yjnoh1016 requested changes
수고많았어요🥰

2021-09-09 11:30 UTC, merged

2021-09-11 03:16 UTC, jihoonahn commented on GOOUT/Controller/SignUpViewController.swift
> +    }
굳이 lazy를 사용하신 이유가 있을까요?

2021-09-11 03:16 UTC, jihoonahn commented on GOOUT/Controller/SignUpViewController.swift
> +class SignUpViewController: UIViewController, UITextFieldDelegate {
이 부분은 
```swift
extension SignUpViewController : UITextFieldDelegate{
 ...scope...
}
```
이렇게 묶어서 사용하면 기능별로 단위를 묶여서 보기 편할 것 같습니다.